---

- name: jenkins-install | Install Jenkins pt. 1
  apt_key: url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key

- name: jenkins-install | Install Jenkins pt. 2
  apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/' update_cache=yes

- name: jenkins-install | Install Jenkins pt. 3
  apt: pkg=jenkins

- name: jenkins-install | Install additional deb packages
  apt: pkg={{item}}
  with_items: jenkins_apt_packages

- name: jenkins-install | Setup passlib
  apt: pkg=python-passlib
  when: jenkins_nginx_auth
