---

- file: path={{jenkins_home}}/updates owner={{jenkins_user}} group={{jenkins_group}} mode=0755 state=directory

- name: jenkins-plugins | Update Jenkins plugin data.
  shell: curl -L http://updates.jenkins-ci.org/update-center.json | sed '1d;$d' > /{{jenkins_home}}/updates/default.json
    creates=/{{jenkins_home}}/updates/default.json

- file: path={{jenkins_home}}/updates/default.json owner={{jenkins_user}} group={{jenkins_group}} mode=0755

- name: jenkins-plugins | Install Jenkins plugins.
  command: java -jar {{jenkins_home}}/jenkins-cli.jar -s {{jenkins_url}}{{jenkins_prefix}} install-plugin {{item}} creates={{jenkins_home}}/plugins/{{item}}.jpi
  sudo_user: "{{ jenkins_user }}"
  with_items: jenkins_plugins
  ignore_errors: yes
  notify: jenkins restart
